name: Releases

on: 
  push:
    branches:
      - main
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ""
        bodyFile: ""
        tag: "test2"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true


